### ISSUE TITLE
Needs --filesystem=home (or something similar)

### ISSUE THREAD

**Issue by x80486** [flathub/net.sourceforge.Chessx#2]
Right now it's impossible to run any engine with `ChessX`. Granting `--filesystem=home` fixes the issue.

**Comment by dgcampea** [comment]
I'm not sure if that's the correct way, the engines are executables and unless they're statically linked it won't work properly.
For a better approach I'd create a shell wrapper (in this case for stockfish):
```sh
#!/bin/sh
flatpak-spawn --host stockfish "$@"
```

Long term, the engines could be bundled with ChessX or provided via extension points although short of patching ChessX source (https://github.com/Isarhamster/chessx/blob/b3e1d57eaa21d709aebe0c660d44cd700f1e6b09/src/database/settings.cpp#L271), it doesn't attempt to detect available engines under *nix or provide options for the user to pass directories to search for them.

**Comment by x80486** [comment]
I actually use Stockfish...and it works fine when I grant `home` access, so that was the reason I filed this one.
